### ISSUE TITLE
Adapt Colors to the new Design System

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#254]
## What

Refactor all Margarita's colors so that they comply with thew ones in the design system:

![image](https://user-images.githubusercontent.com/4160121/81416756-76811580-914a-11ea-99cd-6661c125e88f.png)

## How (lets discuss it)
 
My proposal: just create a `colors.scss` variable file with the colors and gradients that appear in the design system. To use them, we will have to link `margarita.scss` in style resources and just do:

```css
color: $hot-pink;
```

**Other ideas**: utility classes, same api as now (`get-color`), use the function of the color as color name ( main-primary instead of hot-pink), both utility classes and scss vars, etc.

## Tasks

- [ ] Decide the "how".
- [ ] Implement new approach.
- [ ] Implement figma color page in Storybook.
- [ ] Fix breaking changes (see below).

## Breaking changes

No matter how we do this, we will have to refactor hundreds of lines of code. I think they will all be "trivial" changes, until we find a color that it's not in the new Design System. In that case, I suggest creating it as a global scss variable in the project where it's being used.
