### ISSUE TITLE
Add the typographies of the new Design System

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#255]
## What

Add all the typography rules from the Design System to Margarita:

![image](https://user-images.githubusercontent.com/4160121/81420864-ded2f580-9150-11ea-906b-8244ce6e5783.png)

## How (let's discuss it)

I think utility classes are the way to go here. Example:

```html
<h2 class="jumbo">Hello</h2>
```

Other possiblility. The "vue" way with components: `<text-jumbo tag="h2">Hello </text-jumbo>`. Pretty overkill imho, but we won't add global css classes if that's something we want to avoid.

Just to be clear, I think this utility classes should only control: font-size, line-height, font-weight, font-family and their respective responsiveness.

## Tasks

- [ ] Decide the "how".
- [ ] Implement new approach.
- [ ] Implement figma typography page in Storybook.

## Breaking changes

No breaking changes.

**Comment by Samitier** [comment]
closed by https://github.com/holaluz/margarita/pull/327
