### ISSUE TITLE
Add layout components for the new Design System.

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#257]
## What

Add a horizontal/grid layout component that allows us to stack and space UI elements using the spacing properties of the Design System:

![image](https://user-images.githubusercontent.com/4160121/81422720-a680e680-9153-11ea-9390-301ef8afbcb7.png)

Also that it respect container requisites of the design system:

![image](https://user-images.githubusercontent.com/4160121/81423236-7ede4e00-9154-11ea-9e6c-da4c18c305bc.png)

## How (let's discuss it)

I would just do this with an external library to not reinvent the wheel to be honest. Lets just use some layout system that is already proven to work and tweak it so we can use it with the params of our Design System. I don't think its necessary to use `grid` if we combine it with the stack component we will already have.

## Tasks

- [ ] Decide the "how".
- [ ] Implement new approach.
- [ ] Document it.
- [ ] Implement figma layout pages in Storybook.
- [ ] Fix breaking changes (see below)

## Breaking changes

No breaking changes if we do not touch `<ma-grid>, <ma-colum>, etc`. Extremely complicated breaking changes if we do.

**Comment by Samitier** [comment]
Closed by https://github.com/holaluz/margarita/issues/274
