### ISSUE TITLE
Add icons from the Design System

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#258]
## What

Add icons from the Design System:

![image](https://user-images.githubusercontent.com/4160121/81424294-feb8e800-9155-11ea-9b5c-0f01a48f6722.png)

## How (let's discuss it)

I would just refactor `<ma-icon` component. Add new props that allow us to make the "rounded", "squared", "filled" variants.

I have one issue tho. Mainly the "colored" icons. I think all icons should be monocromo so we can change the color by css, but there are some icons in the design system that make no sense without different colors (holaluz logo for example or mastercard logo). 

I would add a different component for those: `<ma-logo`. But I think it should be reflected in the design system because for me an icon and a logo are different things.

## Tasks

- [ ] Decide the "how".
- [ ] Implement new approach.
- [ ] Document it.
- [ ] Implement figma icons pages in Storybook.
- [ ] Fix breaking changes (see below)

## Breaking changes

Mildly complex breaking changes if we refactor `<ma-icon`. We can try to not introduce any breaking change if we set defaults to the new added props.

**Comment by Samitier** [comment]
Closed by https://github.com/holaluz/margarita/issues/369
